apiVersion: v1
imagePullSecrets:
- name: builder-dockercfg-k2r5r
kind: ServiceAccount
metadata:
  creationTimestamp: "2021-03-05T17:37:26Z"
  name: builder
  namespace: robot-shop
  resourceVersion: "1593248"
  selfLink: /api/v1/namespaces/robot-shop/serviceaccounts/builder
  uid: 2be57a9e-d2df-4ed0-a557-6c8295ed899d
secrets:
- name: builder-token-k5nvn
- name: builder-dockercfg-k2r5r
