apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-03-05T17:37:27Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:ports:
          .: {}
          k:{"port":8080,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:service: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-create
    operation: Update
    time: "2021-03-05T17:37:27Z"
  name: cart
  namespace: robot-shop
  resourceVersion: "1593266"
  selfLink: /api/v1/namespaces/robot-shop/services/cart
  uid: 78a3ef64-0385-4cf5-bc1f-2c0979cf6868
spec:
  clusterIP: 172.30.3.125
  clusterIPs:
  - 172.30.3.125
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: cart
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
